{- Problem 2, Project Euler. 
	To get sum call fibCaller. Problem can be found at: http://projecteuler.net/problem=2
	
	Problem:
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-}
fibCaller :: Int
fibCaller = fib2 4000000 0 (1,1)

fib :: Int->Int->(Int,Int)->Int
fib lim sum (x,y)
	|z < lim && even z		=fib (lim) (sum+z)	(y,z)
	|z < lim				=fib (lim) (sum) (y,z)
	|z >= lim				=sum
		where z = x+y